#include <Kitimar/CTSmarts/CTSmarts.hpp>
#include <Kitimar/Molecule/MockMolecule.hpp>

#include <iostream>

// SMILES: CC(=O)[O-]
// Generated by SmiToMock
auto molecule = Kitimar::Molecule::MockIndexMolecule{
    {{6,0,0,1,3,false,false},{6,0,0,3,0,false,false},{8,0,0,1,0,false,false},{8,0,-1,1,0,false,false}},
    {{0,1,1,false,false},{1,2,2,false,false},{1,3,1,false,false}}
};

using namespace Kitimar;

bool isCarbonOfDegree3(auto &mol, auto atom)
{
    // Optimized case: single atom (requires no runtime memory)
    return CTSmarts::match_atom<"[CD3]">(mol, atom);
}

bool isCarboxylCarbon(auto &mol, auto atom)
{
    return CTSmarts::match_atom<"C(=O)O">(mol, atom); // atom matches first SMARTS atom
}

bool isCarboxylDoubleBond(auto &mol, auto bond)
{
    return CTSmarts::match_bond<"O=CO">(mol, bond); // bond matches first SMARTS bond
}

int main()
{
    std::cout << "Is carbon of degree 3: "
              << isCarbonOfDegree3(molecule, get_atom(molecule, 1)) << std::endl;

    std::cout << "Is carboxyl carbon: "
              << isCarboxylCarbon(molecule, get_atom(molecule, 1)) << std::endl;

    // Optimized case: single bond (requires no runtime memory)
    std::cout << "Bond 1 matches \"C=O\": "
              << CTSmarts::match_bond<"C=O">(molecule, get_bond(molecule, 1)) << std::endl;

    std::cout << "Bond 0 matches \"C=O\": "
              << CTSmarts::match_bond<"C=O">(molecule, get_bond(molecule, 0)) << std::endl;

    std::cout << "Bond 1 matches \"O=C\": "
              << CTSmarts::match_bond<"C=O">(molecule, get_bond(molecule, 1)) << std::endl;

    std::cout << "Is carboxyl double bond: "
              << isCarboxylDoubleBond(molecule, get_bond(molecule, 1)) << std::endl;
}
