#include <Kitimar/OpenBabel/OpenBabel.hpp>
#include "../test/TestData.hpp"
#include <gtest/gtest.h>

using namespace Kitimar;

void Agrafiotis_ABCD_part_1(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_1(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_2(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_3(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_4(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_5(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_6(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_7(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_8(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_9(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_10(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_11(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_12(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_13(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_14(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_15(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_16(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_17(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_18(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_19(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_20(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_21(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_22(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_23(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_24(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_25(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_26(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_27(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_28(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_29(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_30(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_31(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_32(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_33(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_34(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_35(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_36(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_37(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_38(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_39(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_40(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_41(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_42(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_43(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_44(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_45(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_46(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_47(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_48(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_49(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_50(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_51(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_52(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_53(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_54(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_55(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_56(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_57(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_58(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_59(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_60(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_61(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_62(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_63(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_64(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_65(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_66(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_67(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_68(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_69(OpenBabel::OBMol &mol);
void BindingDB_substructure_part_70(OpenBabel::OBMol &mol);
void Hicks_and_Jochum_part_1(OpenBabel::OBMol &mol);
void RDKit_smarts_part_1(OpenBabel::OBMol &mol);
void RDKit_smarts_part_2(OpenBabel::OBMol &mol);
void RDKit_smarts_part_3(OpenBabel::OBMol &mol);
void RDKit_smarts_part_4(OpenBabel::OBMol &mol);
void RDKit_smarts_part_5(OpenBabel::OBMol &mol);
void RDKit_smarts_part_6(OpenBabel::OBMol &mol);
void RDKit_smarts_part_7(OpenBabel::OBMol &mol);
void RDKit_smarts_part_8(OpenBabel::OBMol &mol);
void RDKit_smarts_part_9(OpenBabel::OBMol &mol);
void RDMACCS_part_1(OpenBabel::OBMol &mol);
void RDMACCS_part_2(OpenBabel::OBMol &mol);
void RDMACCS_part_3(OpenBabel::OBMol &mol);
void RDMACCS_part_4(OpenBabel::OBMol &mol);
void Rarey_smarts_part_1(OpenBabel::OBMol &mol);
void Rarey_smarts_part_2(OpenBabel::OBMol &mol);
void Rarey_smarts_part_3(OpenBabel::OBMol &mol);
void Rarey_smarts_part_4(OpenBabel::OBMol &mol);
void Rarey_smarts_part_5(OpenBabel::OBMol &mol);
void Rarey_smarts_part_6(OpenBabel::OBMol &mol);
void Rarey_smarts_part_7(OpenBabel::OBMol &mol);
void Rarey_smarts_part_8(OpenBabel::OBMol &mol);
void Rarey_smarts_part_9(OpenBabel::OBMol &mol);
void Rarey_smarts_part_10(OpenBabel::OBMol &mol);
void Rarey_smarts_part_11(OpenBabel::OBMol &mol);
void Rarey_smarts_part_12(OpenBabel::OBMol &mol);
void Rarey_smarts_part_13(OpenBabel::OBMol &mol);
void Rarey_smarts_part_14(OpenBabel::OBMol &mol);
void Rarey_smarts_part_15(OpenBabel::OBMol &mol);
void Rarey_smarts_part_16(OpenBabel::OBMol &mol);
void Rarey_smarts_part_17(OpenBabel::OBMol &mol);
void Rarey_smarts_part_18(OpenBabel::OBMol &mol);
void Rarey_smarts_part_19(OpenBabel::OBMol &mol);
void Rarey_smarts_part_20(OpenBabel::OBMol &mol);
void Rarey_smarts_part_21(OpenBabel::OBMol &mol);
void Rarey_smarts_part_22(OpenBabel::OBMol &mol);
void Rarey_smarts_part_23(OpenBabel::OBMol &mol);
void Rarey_smarts_part_24(OpenBabel::OBMol &mol);
void Rarey_smarts_part_25(OpenBabel::OBMol &mol);

TEST(ValidateCTSmarts, Sqc)
{
    OpenBabelSmilesMolSource source{chembl_smi_filename("100K")};
    auto i = 0;
    for (auto mol : source.molecules()) {
        std::cout << "Molecule: " << ++i << " -- " << writeSmiles(mol) << std::endl;
        Agrafiotis_ABCD_part_1(mol);
        BindingDB_substructure_part_1(mol);
        BindingDB_substructure_part_2(mol);
        BindingDB_substructure_part_3(mol);
        BindingDB_substructure_part_4(mol);
        BindingDB_substructure_part_5(mol);
        BindingDB_substructure_part_6(mol);
        BindingDB_substructure_part_7(mol);
        BindingDB_substructure_part_8(mol);
        BindingDB_substructure_part_9(mol);
        BindingDB_substructure_part_10(mol);
        BindingDB_substructure_part_11(mol);
        BindingDB_substructure_part_12(mol);
        BindingDB_substructure_part_13(mol);
        BindingDB_substructure_part_14(mol);
        BindingDB_substructure_part_15(mol);
        BindingDB_substructure_part_16(mol);
        BindingDB_substructure_part_17(mol);
        BindingDB_substructure_part_18(mol);
        BindingDB_substructure_part_19(mol);
        BindingDB_substructure_part_20(mol);
        BindingDB_substructure_part_21(mol);
        BindingDB_substructure_part_22(mol);
        BindingDB_substructure_part_23(mol);
        BindingDB_substructure_part_24(mol);
        BindingDB_substructure_part_25(mol);
        BindingDB_substructure_part_26(mol);
        BindingDB_substructure_part_27(mol);
        BindingDB_substructure_part_28(mol);
        BindingDB_substructure_part_29(mol);
        BindingDB_substructure_part_30(mol);
        BindingDB_substructure_part_31(mol);
        BindingDB_substructure_part_32(mol);
        BindingDB_substructure_part_33(mol);
        BindingDB_substructure_part_34(mol);
        BindingDB_substructure_part_35(mol);
        BindingDB_substructure_part_36(mol);
        BindingDB_substructure_part_37(mol);
        BindingDB_substructure_part_38(mol);
        BindingDB_substructure_part_39(mol);
        BindingDB_substructure_part_40(mol);
        BindingDB_substructure_part_41(mol);
        BindingDB_substructure_part_42(mol);
        BindingDB_substructure_part_43(mol);
        BindingDB_substructure_part_44(mol);
        BindingDB_substructure_part_45(mol);
        BindingDB_substructure_part_46(mol);
        BindingDB_substructure_part_47(mol);
        BindingDB_substructure_part_48(mol);
        BindingDB_substructure_part_49(mol);
        BindingDB_substructure_part_50(mol);
        BindingDB_substructure_part_51(mol);
        BindingDB_substructure_part_52(mol);
        BindingDB_substructure_part_53(mol);
        BindingDB_substructure_part_54(mol);
        BindingDB_substructure_part_55(mol);
        BindingDB_substructure_part_56(mol);
        BindingDB_substructure_part_57(mol);
        BindingDB_substructure_part_58(mol);
        BindingDB_substructure_part_59(mol);
        BindingDB_substructure_part_60(mol);
        BindingDB_substructure_part_61(mol);
        BindingDB_substructure_part_62(mol);
        BindingDB_substructure_part_63(mol);
        BindingDB_substructure_part_64(mol);
        BindingDB_substructure_part_65(mol);
        BindingDB_substructure_part_66(mol);
        BindingDB_substructure_part_67(mol);
        BindingDB_substructure_part_68(mol);
        BindingDB_substructure_part_69(mol);
        BindingDB_substructure_part_70(mol);
        Hicks_and_Jochum_part_1(mol);
        RDKit_smarts_part_1(mol);
        RDKit_smarts_part_2(mol);
        RDKit_smarts_part_3(mol);
        RDKit_smarts_part_4(mol);
        RDKit_smarts_part_5(mol);
        RDKit_smarts_part_6(mol);
        RDKit_smarts_part_7(mol);
        RDKit_smarts_part_8(mol);
        RDKit_smarts_part_9(mol);
        RDMACCS_part_1(mol);
        RDMACCS_part_2(mol);
        RDMACCS_part_3(mol);
        RDMACCS_part_4(mol);
        Rarey_smarts_part_1(mol);
        Rarey_smarts_part_2(mol);
        Rarey_smarts_part_3(mol);
        Rarey_smarts_part_4(mol);
        Rarey_smarts_part_5(mol);
        Rarey_smarts_part_6(mol);
        Rarey_smarts_part_7(mol);
        Rarey_smarts_part_8(mol);
        Rarey_smarts_part_9(mol);
        Rarey_smarts_part_10(mol);
        Rarey_smarts_part_11(mol);
        Rarey_smarts_part_12(mol);
        Rarey_smarts_part_13(mol);
        Rarey_smarts_part_14(mol);
        Rarey_smarts_part_15(mol);
        Rarey_smarts_part_16(mol);
        Rarey_smarts_part_17(mol);
        Rarey_smarts_part_18(mol);
        Rarey_smarts_part_19(mol);
        Rarey_smarts_part_20(mol);
        Rarey_smarts_part_21(mol);
        Rarey_smarts_part_22(mol);
        Rarey_smarts_part_23(mol);
        Rarey_smarts_part_24(mol);
        Rarey_smarts_part_25(mol);
    }
}
