#include <Kitimar/RDKit/RDKit.hpp>
#include <Kitimar/OpenBabel/OpenBabel.hpp>

using namespace Kitimar;

template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_1(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_2(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_3(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_4(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_5(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_6(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_7(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_8(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_9(Mol &mol);
template<Molecule::Molecule Mol> void Agrafiotis_ABCD_part_10(Mol &mol);
template<Molecule::Molecule Mol> void Hicks_and_Jochum_part_1(Mol &mol);
template<Molecule::Molecule Mol> void Hicks_and_Jochum_part_2(Mol &mol);
template<Molecule::Molecule Mol> void Hicks_and_Jochum_part_3(Mol &mol);
template<Molecule::Molecule Mol> void Hicks_and_Jochum_part_4(Mol &mol);
template<Molecule::Molecule Mol> void Hicks_and_Jochum_part_5(Mol &mol);
template<Molecule::Molecule Mol> void Hicks_and_Jochum_part_6(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_1(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_2(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_3(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_4(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_5(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_6(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_7(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_8(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_9(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_10(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_11(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_12(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_13(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_14(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_15(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_16(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_17(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_18(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_19(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_20(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_21(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_22(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_23(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_24(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_25(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_26(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_27(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_28(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_29(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_30(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_31(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_32(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_33(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_34(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_35(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_36(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_37(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_38(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_39(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_40(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_41(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_42(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_43(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_44(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_45(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_46(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_47(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_48(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_49(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_50(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_51(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_52(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_53(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_54(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_55(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_56(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_57(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_58(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_59(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_60(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_61(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_62(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_63(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_64(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_65(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_66(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_67(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_68(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_69(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_70(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_71(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_72(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_73(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_74(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_75(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_76(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_77(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_78(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_79(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_80(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_81(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_82(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_83(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_84(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_85(Mol &mol);
template<Molecule::Molecule Mol> void RDKit_smarts_part_86(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_1(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_2(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_3(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_4(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_5(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_6(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_7(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_8(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_9(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_10(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_11(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_12(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_13(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_14(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_15(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_16(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_17(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_18(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_19(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_20(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_21(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_22(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_23(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_24(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_25(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_26(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_27(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_28(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_29(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_30(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_31(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_32(Mol &mol);
template<Molecule::Molecule Mol> void RDMACCS_part_33(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_1(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_2(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_3(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_4(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_5(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_6(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_7(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_8(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_9(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_10(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_11(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_12(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_13(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_14(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_15(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_16(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_17(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_18(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_19(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_20(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_21(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_22(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_23(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_24(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_25(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_26(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_27(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_28(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_29(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_30(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_31(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_32(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_33(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_34(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_35(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_36(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_37(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_38(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_39(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_40(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_41(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_42(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_43(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_44(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_45(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_46(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_47(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_48(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_49(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_50(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_51(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_52(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_53(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_54(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_55(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_56(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_57(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_58(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_59(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_60(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_61(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_62(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_63(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_64(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_65(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_66(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_67(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_68(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_69(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_70(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_71(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_72(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_73(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_74(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_75(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_76(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_77(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_78(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_79(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_80(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_81(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_82(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_83(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_84(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_85(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_86(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_87(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_88(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_89(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_90(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_91(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_92(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_93(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_94(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_95(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_96(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_97(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_98(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_99(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_100(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_101(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_102(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_103(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_104(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_105(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_106(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_107(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_108(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_109(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_110(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_111(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_112(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_113(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_114(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_115(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_116(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_117(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_118(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_119(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_120(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_121(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_122(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_123(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_124(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_125(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_126(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_127(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_128(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_129(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_130(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_131(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_132(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_133(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_134(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_135(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_136(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_137(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_138(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_139(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_140(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_141(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_142(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_143(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_144(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_145(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_146(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_147(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_148(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_149(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_150(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_151(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_152(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_153(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_154(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_155(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_156(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_157(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_158(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_159(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_160(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_161(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_162(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_163(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_164(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_165(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_166(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_167(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_168(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_169(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_170(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_171(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_172(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_173(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_174(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_175(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_176(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_177(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_178(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_179(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_180(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_181(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_182(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_183(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_184(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_185(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_186(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_187(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_188(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_189(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_190(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_191(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_192(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_193(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_194(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_195(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_196(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_197(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_198(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_199(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_200(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_201(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_202(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_203(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_204(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_205(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_206(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_207(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_208(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_209(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_210(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_211(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_212(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_213(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_214(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_215(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_216(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_217(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_218(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_219(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_220(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_221(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_222(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_223(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_224(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_225(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_226(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_227(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_228(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_229(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_230(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_231(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_232(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_233(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_234(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_235(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_236(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_237(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_238(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_239(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_240(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_241(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_242(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_243(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_244(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_245(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_246(Mol &mol);
template<Molecule::Molecule Mol> void Rarey_smarts_part_247(Mol &mol);

template<Molecule::Molecule Mol>
void validate_parts(Mol &mol)
{
    Agrafiotis_ABCD_part_1(mol);
    Agrafiotis_ABCD_part_2(mol);
    Agrafiotis_ABCD_part_3(mol);
    Agrafiotis_ABCD_part_4(mol);
    Agrafiotis_ABCD_part_5(mol);
    Agrafiotis_ABCD_part_6(mol);
    Agrafiotis_ABCD_part_7(mol);
    Agrafiotis_ABCD_part_8(mol);
    Agrafiotis_ABCD_part_9(mol);
    Agrafiotis_ABCD_part_10(mol);
    Hicks_and_Jochum_part_1(mol);
    Hicks_and_Jochum_part_2(mol);
    Hicks_and_Jochum_part_3(mol);
    Hicks_and_Jochum_part_4(mol);
    Hicks_and_Jochum_part_5(mol);
    Hicks_and_Jochum_part_6(mol);
    RDKit_smarts_part_1(mol);
    RDKit_smarts_part_2(mol);
    RDKit_smarts_part_3(mol);
    RDKit_smarts_part_4(mol);
    RDKit_smarts_part_5(mol);
    RDKit_smarts_part_6(mol);
    RDKit_smarts_part_7(mol);
    RDKit_smarts_part_8(mol);
    RDKit_smarts_part_9(mol);
    RDKit_smarts_part_10(mol);
    RDKit_smarts_part_11(mol);
    RDKit_smarts_part_12(mol);
    RDKit_smarts_part_13(mol);
    RDKit_smarts_part_14(mol);
    RDKit_smarts_part_15(mol);
    RDKit_smarts_part_16(mol);
    RDKit_smarts_part_17(mol);
    RDKit_smarts_part_18(mol);
    RDKit_smarts_part_19(mol);
    RDKit_smarts_part_20(mol);
    RDKit_smarts_part_21(mol);
    RDKit_smarts_part_22(mol);
    RDKit_smarts_part_23(mol);
    RDKit_smarts_part_24(mol);
    RDKit_smarts_part_25(mol);
    RDKit_smarts_part_26(mol);
    RDKit_smarts_part_27(mol);
    RDKit_smarts_part_28(mol);
    RDKit_smarts_part_29(mol);
    RDKit_smarts_part_30(mol);
    RDKit_smarts_part_31(mol);
    RDKit_smarts_part_32(mol);
    RDKit_smarts_part_33(mol);
    RDKit_smarts_part_34(mol);
    RDKit_smarts_part_35(mol);
    RDKit_smarts_part_36(mol);
    RDKit_smarts_part_37(mol);
    RDKit_smarts_part_38(mol);
    RDKit_smarts_part_39(mol);
    RDKit_smarts_part_40(mol);
    RDKit_smarts_part_41(mol);
    RDKit_smarts_part_42(mol);
    RDKit_smarts_part_43(mol);
    RDKit_smarts_part_44(mol);
    RDKit_smarts_part_45(mol);
    RDKit_smarts_part_46(mol);
    RDKit_smarts_part_47(mol);
    RDKit_smarts_part_48(mol);
    RDKit_smarts_part_49(mol);
    RDKit_smarts_part_50(mol);
    RDKit_smarts_part_51(mol);
    RDKit_smarts_part_52(mol);
    RDKit_smarts_part_53(mol);
    RDKit_smarts_part_54(mol);
    RDKit_smarts_part_55(mol);
    RDKit_smarts_part_56(mol);
    RDKit_smarts_part_57(mol);
    RDKit_smarts_part_58(mol);
    RDKit_smarts_part_59(mol);
    RDKit_smarts_part_60(mol);
    RDKit_smarts_part_61(mol);
    RDKit_smarts_part_62(mol);
    RDKit_smarts_part_63(mol);
    RDKit_smarts_part_64(mol);
    RDKit_smarts_part_65(mol);
    RDKit_smarts_part_66(mol);
    RDKit_smarts_part_67(mol);
    RDKit_smarts_part_68(mol);
    RDKit_smarts_part_69(mol);
    RDKit_smarts_part_70(mol);
    RDKit_smarts_part_71(mol);
    RDKit_smarts_part_72(mol);
    RDKit_smarts_part_73(mol);
    RDKit_smarts_part_74(mol);
    RDKit_smarts_part_75(mol);
    RDKit_smarts_part_76(mol);
    RDKit_smarts_part_77(mol);
    RDKit_smarts_part_78(mol);
    RDKit_smarts_part_79(mol);
    RDKit_smarts_part_80(mol);
    RDKit_smarts_part_81(mol);
    RDKit_smarts_part_82(mol);
    RDKit_smarts_part_83(mol);
    RDKit_smarts_part_84(mol);
    RDKit_smarts_part_85(mol);
    RDKit_smarts_part_86(mol);
    RDMACCS_part_1(mol);
    RDMACCS_part_2(mol);
    RDMACCS_part_3(mol);
    RDMACCS_part_4(mol);
    RDMACCS_part_5(mol);
    RDMACCS_part_6(mol);
    RDMACCS_part_7(mol);
    RDMACCS_part_8(mol);
    RDMACCS_part_9(mol);
    RDMACCS_part_10(mol);
    RDMACCS_part_11(mol);
    RDMACCS_part_12(mol);
    RDMACCS_part_13(mol);
    RDMACCS_part_14(mol);
    RDMACCS_part_15(mol);
    RDMACCS_part_16(mol);
    RDMACCS_part_17(mol);
    RDMACCS_part_18(mol);
    RDMACCS_part_19(mol);
    RDMACCS_part_20(mol);
    RDMACCS_part_21(mol);
    RDMACCS_part_22(mol);
    RDMACCS_part_23(mol);
    RDMACCS_part_24(mol);
    RDMACCS_part_25(mol);
    RDMACCS_part_26(mol);
    RDMACCS_part_27(mol);
    RDMACCS_part_28(mol);
    RDMACCS_part_29(mol);
    RDMACCS_part_30(mol);
    RDMACCS_part_31(mol);
    RDMACCS_part_32(mol);
    RDMACCS_part_33(mol);
    Rarey_smarts_part_1(mol);
    Rarey_smarts_part_2(mol);
    Rarey_smarts_part_3(mol);
    Rarey_smarts_part_4(mol);
    Rarey_smarts_part_5(mol);
    Rarey_smarts_part_6(mol);
    Rarey_smarts_part_7(mol);
    Rarey_smarts_part_8(mol);
    Rarey_smarts_part_9(mol);
    Rarey_smarts_part_10(mol);
    Rarey_smarts_part_11(mol);
    Rarey_smarts_part_12(mol);
    Rarey_smarts_part_13(mol);
    Rarey_smarts_part_14(mol);
    Rarey_smarts_part_15(mol);
    Rarey_smarts_part_16(mol);
    Rarey_smarts_part_17(mol);
    Rarey_smarts_part_18(mol);
    Rarey_smarts_part_19(mol);
    Rarey_smarts_part_20(mol);
    Rarey_smarts_part_21(mol);
    Rarey_smarts_part_22(mol);
    Rarey_smarts_part_23(mol);
    Rarey_smarts_part_24(mol);
    Rarey_smarts_part_25(mol);
    Rarey_smarts_part_26(mol);
    Rarey_smarts_part_27(mol);
    Rarey_smarts_part_28(mol);
    Rarey_smarts_part_29(mol);
    Rarey_smarts_part_30(mol);
    Rarey_smarts_part_31(mol);
    Rarey_smarts_part_32(mol);
    Rarey_smarts_part_33(mol);
    Rarey_smarts_part_34(mol);
    Rarey_smarts_part_35(mol);
    Rarey_smarts_part_36(mol);
    Rarey_smarts_part_37(mol);
    Rarey_smarts_part_38(mol);
    Rarey_smarts_part_39(mol);
    Rarey_smarts_part_40(mol);
    Rarey_smarts_part_41(mol);
    Rarey_smarts_part_42(mol);
    Rarey_smarts_part_43(mol);
    Rarey_smarts_part_44(mol);
    Rarey_smarts_part_45(mol);
    Rarey_smarts_part_46(mol);
    Rarey_smarts_part_47(mol);
    Rarey_smarts_part_48(mol);
    Rarey_smarts_part_49(mol);
    Rarey_smarts_part_50(mol);
    Rarey_smarts_part_51(mol);
    Rarey_smarts_part_52(mol);
    Rarey_smarts_part_53(mol);
    Rarey_smarts_part_54(mol);
    Rarey_smarts_part_55(mol);
    Rarey_smarts_part_56(mol);
    Rarey_smarts_part_57(mol);
    Rarey_smarts_part_58(mol);
    Rarey_smarts_part_59(mol);
    Rarey_smarts_part_60(mol);
    Rarey_smarts_part_61(mol);
    Rarey_smarts_part_62(mol);
    Rarey_smarts_part_63(mol);
    Rarey_smarts_part_64(mol);
    Rarey_smarts_part_65(mol);
    Rarey_smarts_part_66(mol);
    Rarey_smarts_part_67(mol);
    Rarey_smarts_part_68(mol);
    Rarey_smarts_part_69(mol);
    Rarey_smarts_part_70(mol);
    Rarey_smarts_part_71(mol);
    Rarey_smarts_part_72(mol);
    Rarey_smarts_part_73(mol);
    Rarey_smarts_part_74(mol);
    Rarey_smarts_part_75(mol);
    Rarey_smarts_part_76(mol);
    Rarey_smarts_part_77(mol);
    Rarey_smarts_part_78(mol);
    Rarey_smarts_part_79(mol);
    Rarey_smarts_part_80(mol);
    Rarey_smarts_part_81(mol);
    Rarey_smarts_part_82(mol);
    Rarey_smarts_part_83(mol);
    Rarey_smarts_part_84(mol);
    Rarey_smarts_part_85(mol);
    Rarey_smarts_part_86(mol);
    Rarey_smarts_part_87(mol);
    Rarey_smarts_part_88(mol);
    Rarey_smarts_part_89(mol);
    Rarey_smarts_part_90(mol);
    Rarey_smarts_part_91(mol);
    Rarey_smarts_part_92(mol);
    Rarey_smarts_part_93(mol);
    Rarey_smarts_part_94(mol);
    Rarey_smarts_part_95(mol);
    Rarey_smarts_part_96(mol);
    Rarey_smarts_part_97(mol);
    Rarey_smarts_part_98(mol);
    Rarey_smarts_part_99(mol);
    Rarey_smarts_part_100(mol);
    Rarey_smarts_part_101(mol);
    Rarey_smarts_part_102(mol);
    Rarey_smarts_part_103(mol);
    Rarey_smarts_part_104(mol);
    Rarey_smarts_part_105(mol);
    Rarey_smarts_part_106(mol);
    Rarey_smarts_part_107(mol);
    Rarey_smarts_part_108(mol);
    Rarey_smarts_part_109(mol);
    Rarey_smarts_part_110(mol);
    Rarey_smarts_part_111(mol);
    Rarey_smarts_part_112(mol);
    Rarey_smarts_part_113(mol);
    Rarey_smarts_part_114(mol);
    Rarey_smarts_part_115(mol);
    Rarey_smarts_part_116(mol);
    Rarey_smarts_part_117(mol);
    Rarey_smarts_part_118(mol);
    Rarey_smarts_part_119(mol);
    Rarey_smarts_part_120(mol);
    Rarey_smarts_part_121(mol);
    Rarey_smarts_part_122(mol);
    Rarey_smarts_part_123(mol);
    Rarey_smarts_part_124(mol);
    Rarey_smarts_part_125(mol);
    Rarey_smarts_part_126(mol);
    Rarey_smarts_part_127(mol);
    Rarey_smarts_part_128(mol);
    Rarey_smarts_part_129(mol);
    Rarey_smarts_part_130(mol);
    Rarey_smarts_part_131(mol);
    Rarey_smarts_part_132(mol);
    Rarey_smarts_part_133(mol);
    Rarey_smarts_part_134(mol);
    Rarey_smarts_part_135(mol);
    Rarey_smarts_part_136(mol);
    Rarey_smarts_part_137(mol);
    Rarey_smarts_part_138(mol);
    Rarey_smarts_part_139(mol);
    Rarey_smarts_part_140(mol);
    Rarey_smarts_part_141(mol);
    Rarey_smarts_part_142(mol);
    Rarey_smarts_part_143(mol);
    Rarey_smarts_part_144(mol);
    Rarey_smarts_part_145(mol);
    Rarey_smarts_part_146(mol);
    Rarey_smarts_part_147(mol);
    Rarey_smarts_part_148(mol);
    Rarey_smarts_part_149(mol);
    Rarey_smarts_part_150(mol);
    Rarey_smarts_part_151(mol);
    Rarey_smarts_part_152(mol);
    Rarey_smarts_part_153(mol);
    Rarey_smarts_part_154(mol);
    Rarey_smarts_part_155(mol);
    Rarey_smarts_part_156(mol);
    Rarey_smarts_part_157(mol);
    Rarey_smarts_part_158(mol);
    Rarey_smarts_part_159(mol);
    Rarey_smarts_part_160(mol);
    Rarey_smarts_part_161(mol);
    Rarey_smarts_part_162(mol);
    Rarey_smarts_part_163(mol);
    Rarey_smarts_part_164(mol);
    Rarey_smarts_part_165(mol);
    Rarey_smarts_part_166(mol);
    Rarey_smarts_part_167(mol);
    Rarey_smarts_part_168(mol);
    Rarey_smarts_part_169(mol);
    Rarey_smarts_part_170(mol);
    Rarey_smarts_part_171(mol);
    Rarey_smarts_part_172(mol);
    Rarey_smarts_part_173(mol);
    Rarey_smarts_part_174(mol);
    Rarey_smarts_part_175(mol);
    Rarey_smarts_part_176(mol);
    Rarey_smarts_part_177(mol);
    Rarey_smarts_part_178(mol);
    Rarey_smarts_part_179(mol);
    Rarey_smarts_part_180(mol);
    Rarey_smarts_part_181(mol);
    Rarey_smarts_part_182(mol);
    Rarey_smarts_part_183(mol);
    Rarey_smarts_part_184(mol);
    Rarey_smarts_part_185(mol);
    Rarey_smarts_part_186(mol);
    Rarey_smarts_part_187(mol);
    Rarey_smarts_part_188(mol);
    Rarey_smarts_part_189(mol);
    Rarey_smarts_part_190(mol);
    Rarey_smarts_part_191(mol);
    Rarey_smarts_part_192(mol);
    Rarey_smarts_part_193(mol);
    Rarey_smarts_part_194(mol);
    Rarey_smarts_part_195(mol);
    Rarey_smarts_part_196(mol);
    Rarey_smarts_part_197(mol);
    Rarey_smarts_part_198(mol);
    Rarey_smarts_part_199(mol);
    Rarey_smarts_part_200(mol);
    Rarey_smarts_part_201(mol);
    Rarey_smarts_part_202(mol);
    Rarey_smarts_part_203(mol);
    Rarey_smarts_part_204(mol);
    Rarey_smarts_part_205(mol);
    Rarey_smarts_part_206(mol);
    Rarey_smarts_part_207(mol);
    Rarey_smarts_part_208(mol);
    Rarey_smarts_part_209(mol);
    Rarey_smarts_part_210(mol);
    Rarey_smarts_part_211(mol);
    Rarey_smarts_part_212(mol);
    Rarey_smarts_part_213(mol);
    Rarey_smarts_part_214(mol);
    Rarey_smarts_part_215(mol);
    Rarey_smarts_part_216(mol);
    Rarey_smarts_part_217(mol);
    Rarey_smarts_part_218(mol);
    Rarey_smarts_part_219(mol);
    Rarey_smarts_part_220(mol);
    Rarey_smarts_part_221(mol);
    Rarey_smarts_part_222(mol);
    Rarey_smarts_part_223(mol);
    Rarey_smarts_part_224(mol);
    Rarey_smarts_part_225(mol);
    Rarey_smarts_part_226(mol);
    Rarey_smarts_part_227(mol);
    Rarey_smarts_part_228(mol);
    Rarey_smarts_part_229(mol);
    Rarey_smarts_part_230(mol);
    Rarey_smarts_part_231(mol);
    Rarey_smarts_part_232(mol);
    Rarey_smarts_part_233(mol);
    Rarey_smarts_part_234(mol);
    Rarey_smarts_part_235(mol);
    Rarey_smarts_part_236(mol);
    Rarey_smarts_part_237(mol);
    Rarey_smarts_part_238(mol);
    Rarey_smarts_part_239(mol);
    Rarey_smarts_part_240(mol);
    Rarey_smarts_part_241(mol);
    Rarey_smarts_part_242(mol);
    Rarey_smarts_part_243(mol);
    Rarey_smarts_part_244(mol);
    Rarey_smarts_part_245(mol);
    Rarey_smarts_part_246(mol);
    Rarey_smarts_part_247(mol);
}

template void validate_parts<OpenBabel::OBMol>(OpenBabel::OBMol &mol);
template void validate_parts<RDKit::ROMol>(RDKit::ROMol &mol);
