set(ValidateCTSmarts_PART_SRCS
    Agrafiotis_ABCD_part_1.cpp
    BindingDB_substructure_part_1.cpp
    BindingDB_substructure_part_2.cpp
    BindingDB_substructure_part_3.cpp
    BindingDB_substructure_part_4.cpp
    BindingDB_substructure_part_5.cpp
    BindingDB_substructure_part_6.cpp
    BindingDB_substructure_part_7.cpp
    BindingDB_substructure_part_8.cpp
    BindingDB_substructure_part_9.cpp
    BindingDB_substructure_part_10.cpp
    BindingDB_substructure_part_11.cpp
    BindingDB_substructure_part_12.cpp
    BindingDB_substructure_part_13.cpp
    BindingDB_substructure_part_14.cpp
    BindingDB_substructure_part_15.cpp
    BindingDB_substructure_part_16.cpp
    BindingDB_substructure_part_17.cpp
    BindingDB_substructure_part_18.cpp
    BindingDB_substructure_part_19.cpp
    BindingDB_substructure_part_20.cpp
    BindingDB_substructure_part_21.cpp
    BindingDB_substructure_part_22.cpp
    BindingDB_substructure_part_23.cpp
    BindingDB_substructure_part_24.cpp
    BindingDB_substructure_part_25.cpp
    BindingDB_substructure_part_26.cpp
    BindingDB_substructure_part_27.cpp
    BindingDB_substructure_part_28.cpp
    BindingDB_substructure_part_29.cpp
    BindingDB_substructure_part_30.cpp
    BindingDB_substructure_part_31.cpp
    BindingDB_substructure_part_32.cpp
    BindingDB_substructure_part_33.cpp
    BindingDB_substructure_part_34.cpp
    BindingDB_substructure_part_35.cpp
    BindingDB_substructure_part_36.cpp
    BindingDB_substructure_part_37.cpp
    BindingDB_substructure_part_38.cpp
    BindingDB_substructure_part_39.cpp
    BindingDB_substructure_part_40.cpp
    BindingDB_substructure_part_41.cpp
    BindingDB_substructure_part_42.cpp
    BindingDB_substructure_part_43.cpp
    BindingDB_substructure_part_44.cpp
    BindingDB_substructure_part_45.cpp
    BindingDB_substructure_part_46.cpp
    BindingDB_substructure_part_47.cpp
    BindingDB_substructure_part_48.cpp
    BindingDB_substructure_part_49.cpp
    BindingDB_substructure_part_50.cpp
    BindingDB_substructure_part_51.cpp
    BindingDB_substructure_part_52.cpp
    BindingDB_substructure_part_53.cpp
    BindingDB_substructure_part_54.cpp
    BindingDB_substructure_part_55.cpp
    BindingDB_substructure_part_56.cpp
    BindingDB_substructure_part_57.cpp
    BindingDB_substructure_part_58.cpp
    BindingDB_substructure_part_59.cpp
    BindingDB_substructure_part_60.cpp
    BindingDB_substructure_part_61.cpp
    BindingDB_substructure_part_62.cpp
    BindingDB_substructure_part_63.cpp
    BindingDB_substructure_part_64.cpp
    BindingDB_substructure_part_65.cpp
    BindingDB_substructure_part_66.cpp
    BindingDB_substructure_part_67.cpp
    BindingDB_substructure_part_68.cpp
    BindingDB_substructure_part_69.cpp
    BindingDB_substructure_part_70.cpp
    Hicks_and_Jochum_part_1.cpp
    RDKit_smarts_part_1.cpp
    RDKit_smarts_part_2.cpp
    RDKit_smarts_part_3.cpp
    RDKit_smarts_part_4.cpp
    RDKit_smarts_part_5.cpp
    RDKit_smarts_part_6.cpp
    RDKit_smarts_part_7.cpp
    RDKit_smarts_part_8.cpp
    RDKit_smarts_part_9.cpp
    RDMACCS_part_1.cpp
    RDMACCS_part_2.cpp
    RDMACCS_part_3.cpp
    RDMACCS_part_4.cpp
    Rarey_smarts_part_1.cpp
    Rarey_smarts_part_2.cpp
    Rarey_smarts_part_3.cpp
    Rarey_smarts_part_4.cpp
    Rarey_smarts_part_5.cpp
    Rarey_smarts_part_6.cpp
    Rarey_smarts_part_7.cpp
    Rarey_smarts_part_8.cpp
    Rarey_smarts_part_9.cpp
    Rarey_smarts_part_10.cpp
    Rarey_smarts_part_11.cpp
    Rarey_smarts_part_12.cpp
    Rarey_smarts_part_13.cpp
    Rarey_smarts_part_14.cpp
    Rarey_smarts_part_15.cpp
    Rarey_smarts_part_16.cpp
    Rarey_smarts_part_17.cpp
    Rarey_smarts_part_18.cpp
    Rarey_smarts_part_19.cpp
    Rarey_smarts_part_20.cpp
    Rarey_smarts_part_21.cpp
    Rarey_smarts_part_22.cpp
    Rarey_smarts_part_23.cpp
    Rarey_smarts_part_24.cpp
    Rarey_smarts_part_25.cpp
)
