set(ValidateCTSmarts_PART_SRCS
    Agrafiotis_ABCD_part_1.cpp
    Hicks_and_Jochum_part_1.cpp
    RDKit_smarts_part_1.cpp
    RDKit_smarts_part_2.cpp
    RDKit_smarts_part_3.cpp
    RDKit_smarts_part_4.cpp
    RDKit_smarts_part_5.cpp
    RDKit_smarts_part_6.cpp
    RDKit_smarts_part_7.cpp
    RDKit_smarts_part_8.cpp
    RDKit_smarts_part_9.cpp
    RDMACCS_part_1.cpp
    RDMACCS_part_2.cpp
    RDMACCS_part_3.cpp
    RDMACCS_part_4.cpp
    Rarey_smarts_part_1.cpp
    Rarey_smarts_part_2.cpp
    Rarey_smarts_part_3.cpp
    Rarey_smarts_part_4.cpp
    Rarey_smarts_part_5.cpp
    Rarey_smarts_part_6.cpp
    Rarey_smarts_part_7.cpp
    Rarey_smarts_part_8.cpp
    Rarey_smarts_part_9.cpp
    Rarey_smarts_part_10.cpp
    Rarey_smarts_part_11.cpp
    Rarey_smarts_part_12.cpp
    Rarey_smarts_part_13.cpp
    Rarey_smarts_part_14.cpp
    Rarey_smarts_part_15.cpp
    Rarey_smarts_part_16.cpp
    Rarey_smarts_part_17.cpp
    Rarey_smarts_part_18.cpp
    Rarey_smarts_part_19.cpp
    Rarey_smarts_part_20.cpp
    Rarey_smarts_part_21.cpp
    Rarey_smarts_part_22.cpp
    Rarey_smarts_part_23.cpp
    Rarey_smarts_part_24.cpp
    Rarey_smarts_part_25.cpp
)
