set(ValidateCTSmarts_PART_SRCS
    Agrafiotis_ABCD_part_1.cpp
    Agrafiotis_ABCD_part_2.cpp
    Agrafiotis_ABCD_part_3.cpp
    Agrafiotis_ABCD_part_4.cpp
    Agrafiotis_ABCD_part_5.cpp
    Agrafiotis_ABCD_part_6.cpp
    Agrafiotis_ABCD_part_7.cpp
    Agrafiotis_ABCD_part_8.cpp
    Agrafiotis_ABCD_part_9.cpp
    Agrafiotis_ABCD_part_10.cpp
    Hicks_and_Jochum_part_1.cpp
    Hicks_and_Jochum_part_2.cpp
    Hicks_and_Jochum_part_3.cpp
    Hicks_and_Jochum_part_4.cpp
    Hicks_and_Jochum_part_5.cpp
    Hicks_and_Jochum_part_6.cpp
    RDKit_smarts_part_1.cpp
    RDKit_smarts_part_2.cpp
    RDKit_smarts_part_3.cpp
    RDKit_smarts_part_4.cpp
    RDKit_smarts_part_5.cpp
    RDKit_smarts_part_6.cpp
    RDKit_smarts_part_7.cpp
    RDKit_smarts_part_8.cpp
    RDKit_smarts_part_9.cpp
    RDKit_smarts_part_10.cpp
    RDKit_smarts_part_11.cpp
    RDKit_smarts_part_12.cpp
    RDKit_smarts_part_13.cpp
    RDKit_smarts_part_14.cpp
    RDKit_smarts_part_15.cpp
    RDKit_smarts_part_16.cpp
    RDKit_smarts_part_17.cpp
    RDKit_smarts_part_18.cpp
    RDKit_smarts_part_19.cpp
    RDKit_smarts_part_20.cpp
    RDKit_smarts_part_21.cpp
    RDKit_smarts_part_22.cpp
    RDKit_smarts_part_23.cpp
    RDKit_smarts_part_24.cpp
    RDKit_smarts_part_25.cpp
    RDKit_smarts_part_26.cpp
    RDKit_smarts_part_27.cpp
    RDKit_smarts_part_28.cpp
    RDKit_smarts_part_29.cpp
    RDKit_smarts_part_30.cpp
    RDKit_smarts_part_31.cpp
    RDKit_smarts_part_32.cpp
    RDKit_smarts_part_33.cpp
    RDKit_smarts_part_34.cpp
    RDKit_smarts_part_35.cpp
    RDKit_smarts_part_36.cpp
    RDKit_smarts_part_37.cpp
    RDKit_smarts_part_38.cpp
    RDKit_smarts_part_39.cpp
    RDKit_smarts_part_40.cpp
    RDKit_smarts_part_41.cpp
    RDKit_smarts_part_42.cpp
    RDKit_smarts_part_43.cpp
    RDKit_smarts_part_44.cpp
    RDKit_smarts_part_45.cpp
    RDKit_smarts_part_46.cpp
    RDKit_smarts_part_47.cpp
    RDKit_smarts_part_48.cpp
    RDKit_smarts_part_49.cpp
    RDKit_smarts_part_50.cpp
    RDKit_smarts_part_51.cpp
    RDKit_smarts_part_52.cpp
    RDKit_smarts_part_53.cpp
    RDKit_smarts_part_54.cpp
    RDKit_smarts_part_55.cpp
    RDKit_smarts_part_56.cpp
    RDKit_smarts_part_57.cpp
    RDKit_smarts_part_58.cpp
    RDKit_smarts_part_59.cpp
    RDKit_smarts_part_60.cpp
    RDKit_smarts_part_61.cpp
    RDKit_smarts_part_62.cpp
    RDKit_smarts_part_63.cpp
    RDKit_smarts_part_64.cpp
    RDKit_smarts_part_65.cpp
    RDKit_smarts_part_66.cpp
    RDKit_smarts_part_67.cpp
    RDKit_smarts_part_68.cpp
    RDKit_smarts_part_69.cpp
    RDKit_smarts_part_70.cpp
    RDKit_smarts_part_71.cpp
    RDKit_smarts_part_72.cpp
    RDKit_smarts_part_73.cpp
    RDKit_smarts_part_74.cpp
    RDKit_smarts_part_75.cpp
    RDKit_smarts_part_76.cpp
    RDKit_smarts_part_77.cpp
    RDKit_smarts_part_78.cpp
    RDKit_smarts_part_79.cpp
    RDKit_smarts_part_80.cpp
    RDKit_smarts_part_81.cpp
    RDKit_smarts_part_82.cpp
    RDKit_smarts_part_83.cpp
    RDKit_smarts_part_84.cpp
    RDKit_smarts_part_85.cpp
    RDKit_smarts_part_86.cpp
    RDMACCS_part_1.cpp
    RDMACCS_part_2.cpp
    RDMACCS_part_3.cpp
    RDMACCS_part_4.cpp
    RDMACCS_part_5.cpp
    RDMACCS_part_6.cpp
    RDMACCS_part_7.cpp
    RDMACCS_part_8.cpp
    RDMACCS_part_9.cpp
    RDMACCS_part_10.cpp
    RDMACCS_part_11.cpp
    RDMACCS_part_12.cpp
    RDMACCS_part_13.cpp
    RDMACCS_part_14.cpp
    RDMACCS_part_15.cpp
    RDMACCS_part_16.cpp
    RDMACCS_part_17.cpp
    RDMACCS_part_18.cpp
    RDMACCS_part_19.cpp
    RDMACCS_part_20.cpp
    RDMACCS_part_21.cpp
    RDMACCS_part_22.cpp
    RDMACCS_part_23.cpp
    RDMACCS_part_24.cpp
    RDMACCS_part_25.cpp
    RDMACCS_part_26.cpp
    RDMACCS_part_27.cpp
    RDMACCS_part_28.cpp
    RDMACCS_part_29.cpp
    RDMACCS_part_30.cpp
    RDMACCS_part_31.cpp
    RDMACCS_part_32.cpp
    RDMACCS_part_33.cpp
    Rarey_smarts_part_1.cpp
    Rarey_smarts_part_2.cpp
    Rarey_smarts_part_3.cpp
    Rarey_smarts_part_4.cpp
    Rarey_smarts_part_5.cpp
    Rarey_smarts_part_6.cpp
    Rarey_smarts_part_7.cpp
    Rarey_smarts_part_8.cpp
    Rarey_smarts_part_9.cpp
    Rarey_smarts_part_10.cpp
    Rarey_smarts_part_11.cpp
    Rarey_smarts_part_12.cpp
    Rarey_smarts_part_13.cpp
    Rarey_smarts_part_14.cpp
    Rarey_smarts_part_15.cpp
    Rarey_smarts_part_16.cpp
    Rarey_smarts_part_17.cpp
    Rarey_smarts_part_18.cpp
    Rarey_smarts_part_19.cpp
    Rarey_smarts_part_20.cpp
    Rarey_smarts_part_21.cpp
    Rarey_smarts_part_22.cpp
    Rarey_smarts_part_23.cpp
    Rarey_smarts_part_24.cpp
    Rarey_smarts_part_25.cpp
    Rarey_smarts_part_26.cpp
    Rarey_smarts_part_27.cpp
    Rarey_smarts_part_28.cpp
    Rarey_smarts_part_29.cpp
    Rarey_smarts_part_30.cpp
    Rarey_smarts_part_31.cpp
    Rarey_smarts_part_32.cpp
    Rarey_smarts_part_33.cpp
    Rarey_smarts_part_34.cpp
    Rarey_smarts_part_35.cpp
    Rarey_smarts_part_36.cpp
    Rarey_smarts_part_37.cpp
    Rarey_smarts_part_38.cpp
    Rarey_smarts_part_39.cpp
    Rarey_smarts_part_40.cpp
    Rarey_smarts_part_41.cpp
    Rarey_smarts_part_42.cpp
    Rarey_smarts_part_43.cpp
    Rarey_smarts_part_44.cpp
    Rarey_smarts_part_45.cpp
    Rarey_smarts_part_46.cpp
    Rarey_smarts_part_47.cpp
    Rarey_smarts_part_48.cpp
    Rarey_smarts_part_49.cpp
    Rarey_smarts_part_50.cpp
    Rarey_smarts_part_51.cpp
    Rarey_smarts_part_52.cpp
    Rarey_smarts_part_53.cpp
    Rarey_smarts_part_54.cpp
    Rarey_smarts_part_55.cpp
    Rarey_smarts_part_56.cpp
    Rarey_smarts_part_57.cpp
    Rarey_smarts_part_58.cpp
    Rarey_smarts_part_59.cpp
    Rarey_smarts_part_60.cpp
    Rarey_smarts_part_61.cpp
    Rarey_smarts_part_62.cpp
    Rarey_smarts_part_63.cpp
    Rarey_smarts_part_64.cpp
    Rarey_smarts_part_65.cpp
    Rarey_smarts_part_66.cpp
    Rarey_smarts_part_67.cpp
    Rarey_smarts_part_68.cpp
    Rarey_smarts_part_69.cpp
    Rarey_smarts_part_70.cpp
    Rarey_smarts_part_71.cpp
    Rarey_smarts_part_72.cpp
    Rarey_smarts_part_73.cpp
    Rarey_smarts_part_74.cpp
    Rarey_smarts_part_75.cpp
    Rarey_smarts_part_76.cpp
    Rarey_smarts_part_77.cpp
    Rarey_smarts_part_78.cpp
    Rarey_smarts_part_79.cpp
    Rarey_smarts_part_80.cpp
    Rarey_smarts_part_81.cpp
    Rarey_smarts_part_82.cpp
    Rarey_smarts_part_83.cpp
    Rarey_smarts_part_84.cpp
    Rarey_smarts_part_85.cpp
    Rarey_smarts_part_86.cpp
    Rarey_smarts_part_87.cpp
    Rarey_smarts_part_88.cpp
    Rarey_smarts_part_89.cpp
    Rarey_smarts_part_90.cpp
    Rarey_smarts_part_91.cpp
    Rarey_smarts_part_92.cpp
    Rarey_smarts_part_93.cpp
    Rarey_smarts_part_94.cpp
    Rarey_smarts_part_95.cpp
    Rarey_smarts_part_96.cpp
    Rarey_smarts_part_97.cpp
    Rarey_smarts_part_98.cpp
    Rarey_smarts_part_99.cpp
    Rarey_smarts_part_100.cpp
    Rarey_smarts_part_101.cpp
    Rarey_smarts_part_102.cpp
    Rarey_smarts_part_103.cpp
    Rarey_smarts_part_104.cpp
    Rarey_smarts_part_105.cpp
    Rarey_smarts_part_106.cpp
    Rarey_smarts_part_107.cpp
    Rarey_smarts_part_108.cpp
    Rarey_smarts_part_109.cpp
    Rarey_smarts_part_110.cpp
    Rarey_smarts_part_111.cpp
    Rarey_smarts_part_112.cpp
    Rarey_smarts_part_113.cpp
    Rarey_smarts_part_114.cpp
    Rarey_smarts_part_115.cpp
    Rarey_smarts_part_116.cpp
    Rarey_smarts_part_117.cpp
    Rarey_smarts_part_118.cpp
    Rarey_smarts_part_119.cpp
    Rarey_smarts_part_120.cpp
    Rarey_smarts_part_121.cpp
    Rarey_smarts_part_122.cpp
    Rarey_smarts_part_123.cpp
    Rarey_smarts_part_124.cpp
    Rarey_smarts_part_125.cpp
    Rarey_smarts_part_126.cpp
    Rarey_smarts_part_127.cpp
    Rarey_smarts_part_128.cpp
    Rarey_smarts_part_129.cpp
    Rarey_smarts_part_130.cpp
    Rarey_smarts_part_131.cpp
    Rarey_smarts_part_132.cpp
    Rarey_smarts_part_133.cpp
    Rarey_smarts_part_134.cpp
    Rarey_smarts_part_135.cpp
    Rarey_smarts_part_136.cpp
    Rarey_smarts_part_137.cpp
    Rarey_smarts_part_138.cpp
    Rarey_smarts_part_139.cpp
    Rarey_smarts_part_140.cpp
    Rarey_smarts_part_141.cpp
    Rarey_smarts_part_142.cpp
    Rarey_smarts_part_143.cpp
    Rarey_smarts_part_144.cpp
    Rarey_smarts_part_145.cpp
    Rarey_smarts_part_146.cpp
    Rarey_smarts_part_147.cpp
    Rarey_smarts_part_148.cpp
    Rarey_smarts_part_149.cpp
    Rarey_smarts_part_150.cpp
    Rarey_smarts_part_151.cpp
    Rarey_smarts_part_152.cpp
    Rarey_smarts_part_153.cpp
    Rarey_smarts_part_154.cpp
    Rarey_smarts_part_155.cpp
    Rarey_smarts_part_156.cpp
    Rarey_smarts_part_157.cpp
    Rarey_smarts_part_158.cpp
    Rarey_smarts_part_159.cpp
    Rarey_smarts_part_160.cpp
    Rarey_smarts_part_161.cpp
    Rarey_smarts_part_162.cpp
    Rarey_smarts_part_163.cpp
    Rarey_smarts_part_164.cpp
    Rarey_smarts_part_165.cpp
    Rarey_smarts_part_166.cpp
    Rarey_smarts_part_167.cpp
    Rarey_smarts_part_168.cpp
    Rarey_smarts_part_169.cpp
    Rarey_smarts_part_170.cpp
    Rarey_smarts_part_171.cpp
    Rarey_smarts_part_172.cpp
    Rarey_smarts_part_173.cpp
    Rarey_smarts_part_174.cpp
    Rarey_smarts_part_175.cpp
    Rarey_smarts_part_176.cpp
    Rarey_smarts_part_177.cpp
    Rarey_smarts_part_178.cpp
    Rarey_smarts_part_179.cpp
    Rarey_smarts_part_180.cpp
    Rarey_smarts_part_181.cpp
    Rarey_smarts_part_182.cpp
    Rarey_smarts_part_183.cpp
    Rarey_smarts_part_184.cpp
    Rarey_smarts_part_185.cpp
    Rarey_smarts_part_186.cpp
    Rarey_smarts_part_187.cpp
    Rarey_smarts_part_188.cpp
    Rarey_smarts_part_189.cpp
    Rarey_smarts_part_190.cpp
    Rarey_smarts_part_191.cpp
    Rarey_smarts_part_192.cpp
    Rarey_smarts_part_193.cpp
    Rarey_smarts_part_194.cpp
    Rarey_smarts_part_195.cpp
    Rarey_smarts_part_196.cpp
    Rarey_smarts_part_197.cpp
    Rarey_smarts_part_198.cpp
    Rarey_smarts_part_199.cpp
    Rarey_smarts_part_200.cpp
    Rarey_smarts_part_201.cpp
    Rarey_smarts_part_202.cpp
    Rarey_smarts_part_203.cpp
    Rarey_smarts_part_204.cpp
    Rarey_smarts_part_205.cpp
    Rarey_smarts_part_206.cpp
    Rarey_smarts_part_207.cpp
    Rarey_smarts_part_208.cpp
    Rarey_smarts_part_209.cpp
    Rarey_smarts_part_210.cpp
    Rarey_smarts_part_211.cpp
    Rarey_smarts_part_212.cpp
    Rarey_smarts_part_213.cpp
    Rarey_smarts_part_214.cpp
    Rarey_smarts_part_215.cpp
    Rarey_smarts_part_216.cpp
    Rarey_smarts_part_217.cpp
    Rarey_smarts_part_218.cpp
    Rarey_smarts_part_219.cpp
    Rarey_smarts_part_220.cpp
    Rarey_smarts_part_221.cpp
    Rarey_smarts_part_222.cpp
    Rarey_smarts_part_223.cpp
    Rarey_smarts_part_224.cpp
    Rarey_smarts_part_225.cpp
    Rarey_smarts_part_226.cpp
    Rarey_smarts_part_227.cpp
    Rarey_smarts_part_228.cpp
    Rarey_smarts_part_229.cpp
    Rarey_smarts_part_230.cpp
    Rarey_smarts_part_231.cpp
    Rarey_smarts_part_232.cpp
    Rarey_smarts_part_233.cpp
    Rarey_smarts_part_234.cpp
    Rarey_smarts_part_235.cpp
    Rarey_smarts_part_236.cpp
    Rarey_smarts_part_237.cpp
    Rarey_smarts_part_238.cpp
    Rarey_smarts_part_239.cpp
    Rarey_smarts_part_240.cpp
    Rarey_smarts_part_241.cpp
    Rarey_smarts_part_242.cpp
    Rarey_smarts_part_243.cpp
    Rarey_smarts_part_244.cpp
    Rarey_smarts_part_245.cpp
    Rarey_smarts_part_246.cpp
    Rarey_smarts_part_247.cpp
    ValidateParts.cpp
)
