#pragma once

#include <Kitimar/CTSmarts/AST.hpp>

namespace Kitimar::CTSmarts {

    // Input file: ../data/chembl_32.smi
    //
    //     # molecules: 2327928
    //     # atoms:     70820782
    //     # bonds:     76611586

    // Atom Primitives

    consteval double expressionFrequency(AliphaticAtom<1>) noexcept { return 3.93105e-05; }
    consteval double expressionFrequency(AliphaticAtom<2>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(AliphaticAtom<3>) noexcept { return 7.82256e-06; }
    consteval double expressionFrequency(AliphaticAtom<4>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(AliphaticAtom<5>) noexcept { return 7.34248e-05; }
    consteval double expressionFrequency(AliphaticAtom<6>) noexcept { return 0.336657; }
    consteval double expressionFrequency(AliphaticAtom<7>) noexcept { return 0.0694763; }
    consteval double expressionFrequency(AliphaticAtom<8>) noexcept { return 0.112434; }
    consteval double expressionFrequency(AliphaticAtom<9>) noexcept { return 0.0141016; }
    consteval double expressionFrequency(AliphaticAtom<10>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<11>) noexcept { return 0.000206013; }
    consteval double expressionFrequency(AliphaticAtom<12>) noexcept { return 1.76502e-06; }
    consteval double expressionFrequency(AliphaticAtom<13>) noexcept { return 1.58146e-06; }
    consteval double expressionFrequency(AliphaticAtom<14>) noexcept { return 5.36848e-05; }
    consteval double expressionFrequency(AliphaticAtom<15>) noexcept { return 0.000760257; }
    consteval double expressionFrequency(AliphaticAtom<16>) noexcept { return 0.00881536; }
    consteval double expressionFrequency(AliphaticAtom<17>) noexcept { return 0.00798674; }
    consteval double expressionFrequency(AliphaticAtom<18>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<19>) noexcept { return 2.1745e-05; }
    consteval double expressionFrequency(AliphaticAtom<20>) noexcept { return 2.1745e-06; }
    consteval double expressionFrequency(AliphaticAtom<21>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<22>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<23>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<24>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<25>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<26>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<27>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<28>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<29>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<30>) noexcept { return 2.32982e-06; }
    consteval double expressionFrequency(AliphaticAtom<31>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<32>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<33>) noexcept { return 3.44532e-06; }
    consteval double expressionFrequency(AliphaticAtom<34>) noexcept { return 2.88475e-05; }
    consteval double expressionFrequency(AliphaticAtom<35>) noexcept { return 0.00166148; }
    consteval double expressionFrequency(AliphaticAtom<36>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(AliphaticAtom<37>) noexcept { return 1.69442e-07; }
    consteval double expressionFrequency(AliphaticAtom<38>) noexcept { return 2.54163e-07; }
    consteval double expressionFrequency(AliphaticAtom<39>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<40>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<41>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<42>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<43>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<44>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<45>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<46>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<47>) noexcept { return 6.07166e-07; }
    consteval double expressionFrequency(AliphaticAtom<48>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<49>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<50>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<51>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<52>) noexcept { return 3.03583e-06; }
    consteval double expressionFrequency(AliphaticAtom<53>) noexcept { return 0.00028654; }
    consteval double expressionFrequency(AliphaticAtom<54>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(AliphaticAtom<55>) noexcept { return 1.12961e-07; }
    consteval double expressionFrequency(AliphaticAtom<56>) noexcept { return 1.69442e-07; }
    consteval double expressionFrequency(AliphaticAtom<57>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<58>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<59>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<60>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<61>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<62>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<63>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<64>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<65>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<66>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<67>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<68>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<69>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<70>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<71>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<72>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<73>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<74>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<75>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<76>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<77>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<78>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<79>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<80>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<81>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<82>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<83>) noexcept { return 7.06007e-08; }
    consteval double expressionFrequency(AliphaticAtom<84>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<85>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(AliphaticAtom<86>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<87>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<88>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(AliphaticAtom<89>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<90>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<91>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<92>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<93>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<94>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<95>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<96>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<97>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<98>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<99>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<100>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<101>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<102>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<103>) noexcept { return 0; }
    consteval double expressionFrequency(AliphaticAtom<104>) noexcept { return 0; }
    consteval double expressionFrequency(Element<1>) noexcept { return 3.93105e-05; }
    consteval double expressionFrequency(Element<2>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Element<3>) noexcept { return 7.82256e-06; }
    consteval double expressionFrequency(Element<4>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Element<5>) noexcept { return 7.54722e-05; }
    consteval double expressionFrequency(Element<6>) noexcept { return 0.730777; }
    consteval double expressionFrequency(Element<7>) noexcept { return 0.114961; }
    consteval double expressionFrequency(Element<8>) noexcept { return 0.116239; }
    consteval double expressionFrequency(Element<9>) noexcept { return 0.0141016; }
    consteval double expressionFrequency(Element<10>) noexcept { return 0; }
    consteval double expressionFrequency(Element<11>) noexcept { return 0.000206013; }
    consteval double expressionFrequency(Element<12>) noexcept { return 1.76502e-06; }
    consteval double expressionFrequency(Element<13>) noexcept { return 1.58146e-06; }
    consteval double expressionFrequency(Element<14>) noexcept { return 5.36848e-05; }
    consteval double expressionFrequency(Element<15>) noexcept { return 0.00076078; }
    consteval double expressionFrequency(Element<16>) noexcept { return 0.012762; }
    consteval double expressionFrequency(Element<17>) noexcept { return 0.00798674; }
    consteval double expressionFrequency(Element<18>) noexcept { return 0; }
    consteval double expressionFrequency(Element<19>) noexcept { return 2.1745e-05; }
    consteval double expressionFrequency(Element<20>) noexcept { return 2.1745e-06; }
    consteval double expressionFrequency(Element<21>) noexcept { return 0; }
    consteval double expressionFrequency(Element<22>) noexcept { return 0; }
    consteval double expressionFrequency(Element<23>) noexcept { return 0; }
    consteval double expressionFrequency(Element<24>) noexcept { return 0; }
    consteval double expressionFrequency(Element<25>) noexcept { return 0; }
    consteval double expressionFrequency(Element<26>) noexcept { return 0; }
    consteval double expressionFrequency(Element<27>) noexcept { return 0; }
    consteval double expressionFrequency(Element<28>) noexcept { return 0; }
    consteval double expressionFrequency(Element<29>) noexcept { return 0; }
    consteval double expressionFrequency(Element<30>) noexcept { return 2.32982e-06; }
    consteval double expressionFrequency(Element<31>) noexcept { return 0; }
    consteval double expressionFrequency(Element<32>) noexcept { return 0; }
    consteval double expressionFrequency(Element<33>) noexcept { return 3.51592e-06; }
    consteval double expressionFrequency(Element<34>) noexcept { return 4.37725e-05; }
    consteval double expressionFrequency(Element<35>) noexcept { return 0.00166148; }
    consteval double expressionFrequency(Element<36>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Element<37>) noexcept { return 1.69442e-07; }
    consteval double expressionFrequency(Element<38>) noexcept { return 2.54163e-07; }
    consteval double expressionFrequency(Element<39>) noexcept { return 0; }
    consteval double expressionFrequency(Element<40>) noexcept { return 0; }
    consteval double expressionFrequency(Element<41>) noexcept { return 0; }
    consteval double expressionFrequency(Element<42>) noexcept { return 0; }
    consteval double expressionFrequency(Element<43>) noexcept { return 0; }
    consteval double expressionFrequency(Element<44>) noexcept { return 0; }
    consteval double expressionFrequency(Element<45>) noexcept { return 0; }
    consteval double expressionFrequency(Element<46>) noexcept { return 0; }
    consteval double expressionFrequency(Element<47>) noexcept { return 6.07166e-07; }
    consteval double expressionFrequency(Element<48>) noexcept { return 0; }
    consteval double expressionFrequency(Element<49>) noexcept { return 0; }
    consteval double expressionFrequency(Element<50>) noexcept { return 0; }
    consteval double expressionFrequency(Element<51>) noexcept { return 0; }
    consteval double expressionFrequency(Element<52>) noexcept { return 3.03583e-06; }
    consteval double expressionFrequency(Element<53>) noexcept { return 0.00028654; }
    consteval double expressionFrequency(Element<54>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(Element<55>) noexcept { return 1.12961e-07; }
    consteval double expressionFrequency(Element<56>) noexcept { return 1.69442e-07; }
    consteval double expressionFrequency(Element<57>) noexcept { return 0; }
    consteval double expressionFrequency(Element<58>) noexcept { return 0; }
    consteval double expressionFrequency(Element<59>) noexcept { return 0; }
    consteval double expressionFrequency(Element<60>) noexcept { return 0; }
    consteval double expressionFrequency(Element<61>) noexcept { return 0; }
    consteval double expressionFrequency(Element<62>) noexcept { return 0; }
    consteval double expressionFrequency(Element<63>) noexcept { return 0; }
    consteval double expressionFrequency(Element<64>) noexcept { return 0; }
    consteval double expressionFrequency(Element<65>) noexcept { return 0; }
    consteval double expressionFrequency(Element<66>) noexcept { return 0; }
    consteval double expressionFrequency(Element<67>) noexcept { return 0; }
    consteval double expressionFrequency(Element<68>) noexcept { return 0; }
    consteval double expressionFrequency(Element<69>) noexcept { return 0; }
    consteval double expressionFrequency(Element<70>) noexcept { return 0; }
    consteval double expressionFrequency(Element<71>) noexcept { return 0; }
    consteval double expressionFrequency(Element<72>) noexcept { return 0; }
    consteval double expressionFrequency(Element<73>) noexcept { return 0; }
    consteval double expressionFrequency(Element<74>) noexcept { return 0; }
    consteval double expressionFrequency(Element<75>) noexcept { return 0; }
    consteval double expressionFrequency(Element<76>) noexcept { return 0; }
    consteval double expressionFrequency(Element<77>) noexcept { return 0; }
    consteval double expressionFrequency(Element<78>) noexcept { return 0; }
    consteval double expressionFrequency(Element<79>) noexcept { return 0; }
    consteval double expressionFrequency(Element<80>) noexcept { return 0; }
    consteval double expressionFrequency(Element<81>) noexcept { return 0; }
    consteval double expressionFrequency(Element<82>) noexcept { return 0; }
    consteval double expressionFrequency(Element<83>) noexcept { return 7.06007e-08; }
    consteval double expressionFrequency(Element<84>) noexcept { return 0; }
    consteval double expressionFrequency(Element<85>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(Element<86>) noexcept { return 0; }
    consteval double expressionFrequency(Element<87>) noexcept { return 0; }
    consteval double expressionFrequency(Element<88>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(Element<89>) noexcept { return 0; }
    consteval double expressionFrequency(Element<90>) noexcept { return 0; }
    consteval double expressionFrequency(Element<91>) noexcept { return 0; }
    consteval double expressionFrequency(Element<92>) noexcept { return 0; }
    consteval double expressionFrequency(Element<93>) noexcept { return 0; }
    consteval double expressionFrequency(Element<94>) noexcept { return 0; }
    consteval double expressionFrequency(Element<95>) noexcept { return 0; }
    consteval double expressionFrequency(Element<96>) noexcept { return 0; }
    consteval double expressionFrequency(Element<97>) noexcept { return 0; }
    consteval double expressionFrequency(Element<98>) noexcept { return 0; }
    consteval double expressionFrequency(Element<99>) noexcept { return 0; }
    consteval double expressionFrequency(Element<100>) noexcept { return 0; }
    consteval double expressionFrequency(Element<101>) noexcept { return 0; }
    consteval double expressionFrequency(Element<102>) noexcept { return 0; }
    consteval double expressionFrequency(Element<103>) noexcept { return 0; }
    consteval double expressionFrequency(Element<104>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<0>) noexcept { return 0.999937; }
    consteval double expressionFrequency(Isotope<1>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<2>) noexcept { return 3.22504e-05; }
    consteval double expressionFrequency(Isotope<3>) noexcept { return 6.83415e-06; }
    consteval double expressionFrequency(Isotope<4>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Isotope<5>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<6>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<7>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<8>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<9>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<10>) noexcept { return 4.23604e-08; }
    consteval double expressionFrequency(Isotope<11>) noexcept { return 4.63141e-06; }
    consteval double expressionFrequency(Isotope<12>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<13>) noexcept { return 5.22446e-07; }
    consteval double expressionFrequency(Isotope<14>) noexcept { return 3.12055e-06; }
    consteval double expressionFrequency(Isotope<15>) noexcept { return 1.27081e-07; }
    consteval double expressionFrequency(Isotope<16>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<17>) noexcept { return 8.47209e-08; }
    consteval double expressionFrequency(Isotope<18>) noexcept { return 7.46956e-06; }
    consteval double expressionFrequency(Isotope<19>) noexcept { return 1.55322e-07; }
    consteval double expressionFrequency(Isotope<20>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<21>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<22>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<23>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<24>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<25>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<26>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<27>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<28>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<29>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<30>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<31>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<32>) noexcept { return 9.8841e-08; }
    consteval double expressionFrequency(Isotope<33>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<34>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<35>) noexcept { return 8.47209e-08; }
    consteval double expressionFrequency(Isotope<36>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<37>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<38>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<39>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<40>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<41>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<42>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<43>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<44>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<45>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<46>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<47>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<48>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<49>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<50>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<51>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<52>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<53>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<54>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<55>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<56>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<57>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<58>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<59>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<60>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<61>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<62>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<63>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<64>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<65>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<66>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<67>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<68>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<69>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<70>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<71>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<72>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<73>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<74>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<75>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Isotope<76>) noexcept { return 5.64806e-08; }
    consteval double expressionFrequency(Isotope<77>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<78>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<79>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<80>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<81>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<82>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Isotope<83>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<84>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<85>) noexcept { return 4.23604e-08; }
    consteval double expressionFrequency(Isotope<86>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<87>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<88>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<89>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<90>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<91>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<92>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<93>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<94>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<95>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<96>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<97>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<98>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<99>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<100>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<101>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<102>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<103>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<104>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<105>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<106>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<107>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<108>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<109>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<110>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<111>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<112>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<113>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<114>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<115>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<116>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<117>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<118>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<119>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<120>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<121>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<122>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<123>) noexcept { return 1.28493e-06; }
    consteval double expressionFrequency(Isotope<124>) noexcept { return 2.40043e-07; }
    consteval double expressionFrequency(Isotope<125>) noexcept { return 4.63141e-06; }
    consteval double expressionFrequency(Isotope<126>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<127>) noexcept { return 7.06007e-08; }
    consteval double expressionFrequency(Isotope<128>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<129>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<130>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<131>) noexcept { return 8.47209e-07; }
    consteval double expressionFrequency(Isotope<132>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<133>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<134>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<135>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Isotope<136>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<137>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<138>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<139>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<140>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<141>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<142>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<143>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<144>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<145>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<146>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<147>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<148>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<149>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<150>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<151>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<152>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<153>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<154>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<155>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<156>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<157>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<158>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<159>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<160>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<161>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<162>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<163>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<164>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<165>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<166>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<167>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<168>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<169>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<170>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<171>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<172>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<173>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<174>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<175>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<176>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<177>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<178>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<179>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<180>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<181>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<182>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<183>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<184>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<185>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<186>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<187>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<188>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<189>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<190>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<191>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<192>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<193>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<194>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<195>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<196>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<197>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<198>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<199>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<200>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<201>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<202>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<203>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<204>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<205>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<206>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<207>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<208>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<209>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<210>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<211>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Isotope<212>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<213>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<214>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<215>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<216>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<217>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<218>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<219>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<220>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<221>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<222>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<223>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Isotope<224>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<225>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<226>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<227>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<228>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<229>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<230>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<231>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<232>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<233>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<234>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<235>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<236>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<237>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<238>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<239>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<240>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<241>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<242>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<243>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<244>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<245>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<246>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<247>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<248>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<249>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<250>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<251>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<252>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<253>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<254>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<255>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<256>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<257>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<258>) noexcept { return 0; }
    consteval double expressionFrequency(Isotope<259>) noexcept { return 0; }
    consteval double expressionFrequency(Degree<0>) noexcept { return 0.00139034; }
    consteval double expressionFrequency(Degree<1>) noexcept { return 0.177861; }
    consteval double expressionFrequency(Degree<2>) noexcept { return 0.494514; }
    consteval double expressionFrequency(Degree<3>) noexcept { return 0.308317; }
    consteval double expressionFrequency(Degree<4>) noexcept { return 0.0179073; }
    consteval double expressionFrequency(Degree<5>) noexcept { return 4.65965e-07; }
    consteval double expressionFrequency(Degree<6>) noexcept { return 1.07737e-05; }
    consteval double expressionFrequency(Degree<7>) noexcept { return 0; }
    consteval double expressionFrequency(Degree<8>) noexcept { return 0; }
    consteval double expressionFrequency(Degree<9>) noexcept { return 0; }
    consteval double expressionFrequency(Valence<0>) noexcept { return 0.000502268; }
    consteval double expressionFrequency(Valence<1>) noexcept { return 0.0256453; }
    consteval double expressionFrequency(Valence<2>) noexcept { return 0.122607; }
    consteval double expressionFrequency(Valence<3>) noexcept { return 0.112946; }
    consteval double expressionFrequency(Valence<4>) noexcept { return 0.73301; }
    consteval double expressionFrequency(Valence<5>) noexcept { return 0.000728077; }
    consteval double expressionFrequency(Valence<6>) noexcept { return 0.00455227; }
    consteval double expressionFrequency(Valence<7>) noexcept { return 8.85333e-06; }
    consteval double expressionFrequency(Valence<8>) noexcept { return 0; }
    consteval double expressionFrequency(Valence<9>) noexcept { return 0; }
    consteval double expressionFrequency(Connectivity<0>) noexcept { return 0.000502268; }
    consteval double expressionFrequency(Connectivity<1>) noexcept { return 0.0893646; }
    consteval double expressionFrequency(Connectivity<2>) noexcept { return 0.0976979; }
    consteval double expressionFrequency(Connectivity<3>) noexcept { return 0.537168; }
    consteval double expressionFrequency(Connectivity<4>) noexcept { return 0.275251; }
    consteval double expressionFrequency(Connectivity<5>) noexcept { return 5.7469e-06; }
    consteval double expressionFrequency(Connectivity<6>) noexcept { return 1.06184e-05; }
    consteval double expressionFrequency(Connectivity<7>) noexcept { return 1.83562e-07; }
    consteval double expressionFrequency(Connectivity<8>) noexcept { return 0; }
    consteval double expressionFrequency(Connectivity<9>) noexcept { return 0; }
    consteval double expressionFrequency(TotalH<0>) noexcept { return 0.443283; }
    consteval double expressionFrequency(TotalH<1>) noexcept { return 0.3401; }
    consteval double expressionFrequency(TotalH<2>) noexcept { return 0.156087; }
    consteval double expressionFrequency(TotalH<3>) noexcept { return 0.0605291; }
    consteval double expressionFrequency(TotalH<4>) noexcept { return 1.00253e-06; }
    consteval double expressionFrequency(TotalH<5>) noexcept { return 0; }
    consteval double expressionFrequency(TotalH<6>) noexcept { return 0; }
    consteval double expressionFrequency(TotalH<7>) noexcept { return 0; }
    consteval double expressionFrequency(TotalH<8>) noexcept { return 0; }
    consteval double expressionFrequency(TotalH<9>) noexcept { return 0; }
    consteval double expressionFrequency(ImplicitH<0>) noexcept { return 0.4433; }
    consteval double expressionFrequency(ImplicitH<1>) noexcept { return 0.340096; }
    consteval double expressionFrequency(ImplicitH<2>) noexcept { return 0.156082; }
    consteval double expressionFrequency(ImplicitH<3>) noexcept { return 0.0605208; }
    consteval double expressionFrequency(ImplicitH<4>) noexcept { return 1.00253e-06; }
    consteval double expressionFrequency(ImplicitH<5>) noexcept { return 0; }
    consteval double expressionFrequency(ImplicitH<6>) noexcept { return 0; }
    consteval double expressionFrequency(ImplicitH<7>) noexcept { return 0; }
    consteval double expressionFrequency(ImplicitH<8>) noexcept { return 0; }
    consteval double expressionFrequency(ImplicitH<9>) noexcept { return 0; }
    consteval double expressionFrequency(RingCount<0>) noexcept { return 0.385299; }
    consteval double expressionFrequency(RingCount<1>) noexcept { return 0.55596; }
    consteval double expressionFrequency(RingCount<2>) noexcept { return 0.0571221; }
    consteval double expressionFrequency(RingCount<3>) noexcept { return 0.00146996; }
    consteval double expressionFrequency(RingCount<4>) noexcept { return 0.000140721; }
    consteval double expressionFrequency(RingCount<5>) noexcept { return 7.80844e-06; }
    consteval double expressionFrequency(RingCount<6>) noexcept { return 8.47209e-08; }
    consteval double expressionFrequency(RingCount<7>) noexcept { return 0; }
    consteval double expressionFrequency(RingCount<8>) noexcept { return 0; }
    consteval double expressionFrequency(RingCount<9>) noexcept { return 0; }
    consteval double expressionFrequency(RingSize<0>) noexcept { return 0; }
    consteval double expressionFrequency(RingSize<1>) noexcept { return 0; }
    consteval double expressionFrequency(RingSize<2>) noexcept { return 0; }
    consteval double expressionFrequency(RingSize<3>) noexcept { return 0.00468978; }
    consteval double expressionFrequency(RingSize<4>) noexcept { return 0.00342536; }
    consteval double expressionFrequency(RingSize<5>) noexcept { return 0.142005; }
    consteval double expressionFrequency(RingSize<6>) noexcept { return 0.473077; }
    consteval double expressionFrequency(RingSize<7>) noexcept { return 0.00944029; }
    consteval double expressionFrequency(RingSize<8>) noexcept { return 0.00140493; }
    consteval double expressionFrequency(RingSize<9>) noexcept { return 0.000360869; }
    consteval double expressionFrequency(RingConnectivity<0>) noexcept { return 0.384489; }
    consteval double expressionFrequency(RingConnectivity<1>) noexcept { return 0; }
    consteval double expressionFrequency(RingConnectivity<2>) noexcept { return 0.5591; }
    consteval double expressionFrequency(RingConnectivity<3>) noexcept { return 0.0550322; }
    consteval double expressionFrequency(RingConnectivity<4>) noexcept { return 0.00137889; }
    consteval double expressionFrequency(RingConnectivity<5>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(RingConnectivity<6>) noexcept { return 0; }
    consteval double expressionFrequency(RingConnectivity<7>) noexcept { return 0; }
    consteval double expressionFrequency(RingConnectivity<8>) noexcept { return 0; }
    consteval double expressionFrequency(RingConnectivity<9>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-15>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-14>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-13>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-12>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-11>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-10>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-9>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-8>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-7>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-6>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-5>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<-4>) noexcept { return 1.41201e-08; }
    consteval double expressionFrequency(Charge<-3>) noexcept { return 2.82403e-08; }
    consteval double expressionFrequency(Charge<-2>) noexcept { return 1.12961e-07; }
    consteval double expressionFrequency(Charge<-1>) noexcept { return 0.00219702; }
    consteval double expressionFrequency(Charge<0>) noexcept { return 0.995261; }
    consteval double expressionFrequency(Charge<1>) noexcept { return 0.00253558; }
    consteval double expressionFrequency(Charge<2>) noexcept { return 5.78926e-06; }
    consteval double expressionFrequency(Charge<3>) noexcept { return 5.64806e-07; }
    consteval double expressionFrequency(Charge<4>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<5>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<6>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<7>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<8>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<9>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<10>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<11>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<12>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<13>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<14>) noexcept { return 0; }
    consteval double expressionFrequency(Charge<15>) noexcept { return 0; }
    consteval double expressionFrequency(AromaticAtom<5>) noexcept { return 2.04742e-06; }
    consteval double expressionFrequency(AromaticAtom<6>) noexcept { return 0.39412; }
    consteval double expressionFrequency(AromaticAtom<7>) noexcept { return 0.0454846; }
    consteval double expressionFrequency(AromaticAtom<8>) noexcept { return 0.00380539; }
    consteval double expressionFrequency(AromaticAtom<15>) noexcept { return 5.22446e-07; }
    consteval double expressionFrequency(AromaticAtom<16>) noexcept { return 0.00394665; }
    consteval double expressionFrequency(AromaticAtom<33>) noexcept { return 7.06007e-08; }
    consteval double expressionFrequency(AromaticAtom<34>) noexcept { return 1.4925e-05; }
    consteval double expressionFrequency(AnyAtom) noexcept { return 1; }
    consteval double expressionFrequency(AnyAliphatic) noexcept { return 0.552626; }
    consteval double expressionFrequency(AnyAromatic) noexcept { return 0.447374; }
    consteval double expressionFrequency(Cyclic) noexcept { return 0.615511; }
    consteval double expressionFrequency(Acyclic) noexcept { return 0.384489; }

    // Bond Primitives

    consteval double expressionFrequency(ImplicitBond) noexcept { return 0.930209; }
    consteval double expressionFrequency(AnyBond) noexcept { return 1; }
    consteval double expressionFrequency(AromaticBond) noexcept { return 0.425489; }
    consteval double expressionFrequency(RingBond) noexcept { return 0.595697; }
    consteval double expressionFrequency(BondOrder<1>) noexcept { return 0.50472; }
    consteval double expressionFrequency(BondOrder<2>) noexcept { return 0.0678171; }
    consteval double expressionFrequency(BondOrder<3>) noexcept { return 0.00197385; }
    consteval double expressionFrequency(BondOrder<4>) noexcept { return 0; }

} // namespace Kitimar::CTSmarts
