#include <Kitimar/CTSmarts/CTSmarts.hpp>
#include <gtest/gtest.h>

using namespace Kitimar;
using namespace Kitimar::CTSmarts;

auto mockAcetateAnion()
{
    // SMILES: CC(=O)[O-]
    // Generated by SmiToMock
    auto mol = Kitimar::Molecule::MockMolecule{
        {{6,0,0,1,3,false,false},{6,0,0,3,0,false,false},{8,0,0,1,0,false,false},{8,0,-1,1,0,false,false}},
        {{0,1,1,false,false},{1,2,2,false,false},{1,3,1,false,false}}
    };
    return mol;
}

TEST(TestCTSmartsMatch, CTSmarts_count)
{
    auto mol = mockAcetateAnion(); // CC(=O)[O-]

    // single atom
    EXPECT_EQ(ctse::count<"C">(mol, ctse::Unique), 2);
    EXPECT_EQ(ctse::count<"O">(mol, ctse::Unique), 2);
    EXPECT_EQ(ctse::count<"[O-]">(mol, ctse::Unique), 1);

    EXPECT_EQ(ctse::count<"N">(mol, ctse::Unique), 0);
    EXPECT_EQ(ctse::count<"[O+]">(mol, ctse::Unique), 0);

    // single bond
    EXPECT_EQ(ctse::count<"CC">(mol, ctse::Unique), 1);
    EXPECT_EQ(ctse::count<"C=O">(mol, ctse::Unique), 1);
    EXPECT_EQ(ctse::count<"C[O-]">(mol, ctse::Unique), 1);

    EXPECT_EQ(ctse::count<"C=C">(mol, ctse::Unique), 0);
    EXPECT_EQ(ctse::count<"C#O">(mol, ctse::Unique), 0);
    EXPECT_EQ(ctse::count<"C[O+]">(mol, ctse::Unique), 0);

    // general case
    EXPECT_EQ(ctse::count<"CC(=O)[O-]">(mol, ctse::Unique), 1);
    EXPECT_EQ(ctse::count<"CC([O-])=O">(mol, ctse::Unique), 1);
    EXPECT_EQ(ctse::count<"O=C(C)[O-]">(mol, ctse::Unique), 1);

    EXPECT_EQ(ctse::count<"CC(=O)N">(mol, ctse::Unique), 0);


    // single atom
    EXPECT_EQ(ctse::count<"C">(mol, ctse::All), 2);
    EXPECT_EQ(ctse::count<"O">(mol, ctse::All), 2);
    EXPECT_EQ(ctse::count<"[O-]">(mol, ctse::All), 1);

    EXPECT_EQ(ctse::count<"N">(mol, ctse::All), 0);
    EXPECT_EQ(ctse::count<"[O+]">(mol, ctse::All), 0);

    // single bond
    EXPECT_EQ(ctse::count<"CC">(mol, ctse::All), 2);
    EXPECT_EQ(ctse::count<"C=O">(mol, ctse::All), 1);
    EXPECT_EQ(ctse::count<"C[O-]">(mol, ctse::All), 1);

    EXPECT_EQ(ctse::count<"C=C">(mol, ctse::All), 0);
    EXPECT_EQ(ctse::count<"C#O">(mol, ctse::All), 0);
    EXPECT_EQ(ctse::count<"C[O+]">(mol, ctse::All), 0);

    // general case
    EXPECT_EQ(ctse::count<"CC(~O)~O">(mol, ctse::All), 2);
    EXPECT_EQ(ctse::count<"CC(=O)[O-]">(mol, ctse::All), 1);
    EXPECT_EQ(ctse::count<"CC([O-])=O">(mol, ctse::All), 1);
    EXPECT_EQ(ctse::count<"O=C(C)[O-]">(mol, ctse::All), 1);

    EXPECT_EQ(ctse::count<"CC(=O)N">(mol, ctse::All), 0);
}
