name: CMake Build Matrix

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC 12",
            os: ubuntu-latest,
            cc: "gcc-12", cxx: "g++-12",
          }
        - {
            name: "Ubuntu Latest GCC 11",
            os: ubuntu-latest,
            cc: "gcc-11", cxx: "g++-11",
          }
        - {
            name: "Ubuntu Latest Clang 16",
            os: ubuntu-latest,
            cc: "clang-16", cxx: "clang++-16",
          }
        - {
            name: "Ubuntu Latest GCC 12 (RDKit + OpenBabel)",
            os: ubuntu-latest,
            cc: "gcc-12", cxx: "g++-12",
            cmake_args: "-DKitimar_WITH_RDKIT=ON -DKitimar_WITH_OPENBABEL=ON",
          }
        - {
            name: "Windows Latest MSVC x86", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
          }

    steps:
    - name: Check variables
      run: echo "${{runner.os}} ${{matrix.config.os}} ${{matrix.config.cc}}"

    - uses: actions/checkout@v2

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo apt-get -qq remove python3-lldb-14
        sudo ./llvm.sh 16
        sudo apt-get -qq install ninja-build
        sudo apt-get -qq install libopenbabel-dev librdkit-dev libboost-iostreams-dev libboost-filesystem-dev

    - name: Install MSVC Command Prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install ninja
        echo "DEPS=msvc-dependencies-master" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Run CMake
      run: |
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_C_COMPILER=${{matrix.config.cc}} -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} ${{matrix.config.cmake_args}}
      shell: bash

    - name: Build
      run: CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} cmake --build .
      shell: bash
      working-directory: ${{ runner.workspace }}/build

    - name: Test
      if: runner.os != 'Windows'
      working-directory: ${{ runner.workspace }}/build
      run: ctest --output-on-failure
